core/urls.py
from django.urls import path
from core.views import *

app_name = 'core'

urlpatterns = [
    path('', Home, name='Home'),
    path('ajax-contact-form/', AjaxContact),
    path('prediction/<int:id>/', prediction_detail, name='prediction_detail'),
]

whatwillhappen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.
class ContactUs(models.Model):
    email = models.CharField(max_length=200)
    wallet = models.CharField(max_length=200)

    class Meta():
        verbose_name = "Contact Us"
        verbose_name_plural = "Contact Us"

    def __str__(self):
        return self.email
    
class Prediction(models.Model):
    title = models.CharField(max_length=200, verbose_name='title')
    content = models.TextField(verbose_name='content')
    image = models.ImageField(upload_to="predictions/", null=True, blank=True, verbose_name="image")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='create at')

    class Meta:
        ordering = ['created_at']
        verbose_name = 'Prediction'
        verbose_name_plural = 'Predictions'

core/forms.py
from django import forms
from .models import Prediction

class PredictionForm(forms.ModelForm):
    class Meta:
        model = Prediction
        fields = ['title', 'content']

core/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from core.models import ContactUs, Prediction
from django.shortcuts import get_object_or_404
from django.urls import reverse

# url = reverse('prediction_detail', args=[1])
# Create your views here.
def Home(request):
    predictions = Prediction.objects.all()
    return render(request, 'parent.html', {'predictions': predictions})

def prediction_detail(request, id):
    prediction = get_object_or_404(Prediction, id=id)
    context = {
        'prediction': prediction,
        'id':id,
    }
    return render(request, 'prediction_detail.html', context)

def AjaxContact(request):
    email = request.GET['email']
    wallet = request.GET['wallet']

    contact = ContactUs.objects.create(
        email = email,
        wallet = wallet,
    )

    context = {
        'bool': True,
        'message': 'We are glad to be in touch with you. Thanks for submitting'
    }

    return JsonResponse({'context': context})

templates/parent.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- ========== Meta Info ========== -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- ========== Title Block ========== -->
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <!-- ========== Style Link ========== -->
    <link rel="stylesheet" href="{% static 'css/parent.css' %}">
    <!-- ========== Ajax CDN ========== -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <!-- ========== Fav Icon ========== -->
    <link rel="icon" type="image/x-icon" href="{% static 'images/photo_2025-01-30_19-24-58.jpg' %}">
    {% block css %}{% endblock %}
</head>
<body>
    <!-- ========== Loading Page ========== -->
    <div id="loading">
        <div class="loader-content">
            <div class="loader-spinner"></div>
            <p class="loading-text">LOADING ...</p>
        </div>
    </div>
    <!-- ========== Main Page ========== -->
    <main>
        <!-- Main Banner Section -->
        <section class="banner-vid">
            <video id="myVideo" playsinline  preload="metadata" muted>
                <source src="{% static 'images/mainBanner.mp4' %}" type="video/mp4">
                Your browser doesn't support this banner.
            </video>
            <img src="{% static 'images/Animation - 1737911102796.gif' %}" alt="Scroll down gif" width="70" height="70">
        </section>
        <!-- Discription Section -->
        <div class="content">
            <h1>
                <strong class="one">WHAT</strong>
                <em><strong class="two">WILL</strong></em>
                <strong class="three">HAPPEN ?</strong>
            </h1>
            <p>
                Welcome to our visionary NFT collection! 🌟
                Our collection is designed to anticipate future events, 
                providing you with the insights and awareness needed to navigate what’s ahead. 
                We harness the full potential of both the material and metaphysical realms, 
                collaborating with influential figures to unveil highly probable future scenarios. 
                Join us on this journey to stay ahead of the curve and be prepared for the future.
            </p>
        </div>
        <!-- Second Banner Section -->
        <section class="eye-vid-container">
            <video id="eye-vid" autoplay loop muted playsinline preload="metadata">
                <source src="{% static 'images/7938.mp4' %}" type="video/mp4">
            </video>
        </section>
        <!-- Road Map Section -->
        <section id="roadmap">
            <h1>Future Roadmap</h1>
            <div class="predictions">
                {% for prediction in predictions %}
                <a href="{% url 'core:prediction_detail' prediction.id %}" class="circle">
                    <div class="circle-img">
                        <img src="{{ prediction.image.url }}" alt="Image">
                    </div>
                    <div class="circle-title">{{ prediction.title }}</div>
                </a>
                {% endfor %}
            </div>
        </section>
        <!-- Members of team Section -->
        <section class="my-team">
            <h1>OUR TEAM MEMBERS</h1>
            <ul class="members" id="members">
                <li>
                    <video muted class="member-video" preload="metadata" playsinline autoplay>
                        <source src="{% static '/images/8070.mp4' %}" type="video/mp4">
                    </video>
                    <h4>Coach</h4>
                    <h5>Alone Mask</h5>
                </li>
                <li>
                    <video muted class="member-video" preload="metadata" playsinline autoplay>
                        <source src="{% static '/images/8056.mp4' %}" type="video/mp4">
                    </video>
                    <h4>Head</h4>
                    <h5>Behnad13</h5>
                </li>
                <li>
                    <video muted class="member-video" preload="metadata" playsinline autoplay>
                        <source src="{% static '/images/8060.mp4' %}" type="video/mp4">
                    </video>
                    <h4>Artist</h4>
                    <h5>Wangock</h5>
                </li>
                <li>                    
                    <video muted class="member-video" preload="metadata" playsinline autoplay>
                        <source src="{% static '/images/8058.mp4' %}" type="video/mp4">
                    </video>
                    <h4>Wizard</h4>
                    <h5>iA</h5>
                </li>
                <li>
                    <video muted class="member-video" preload="metadata" playsinline autoplay>
                        <source src="{% static '/images/8061.mp4' %}" type="video/mp4">
                    </video>
                    <h4>Handeling</h4>
                    <h5>Beaz</h5>
                </li>
            </ul>
        </section>
        <!-- Contact Section -->
        <section class="contact-us">
            <section class="form">
                <form action="" method="POST" id="contact-form">
                    {% csrf_token %}
                    <input type="email" id="email" placeholder="Your Email" required>
                    <input type="text" id="wallet" placeholder="Your Wallet">
                    <button type="submit" id="sbtn">Submit</button>
                </form>
            </section>
            <section class="form-header">
                Now! Be in touch with us
            </section>
        </section>
        <section class="social">
            <section class="social-header">
                Follow us in socials
            </section>
            <section class="social-icons">
                <ul>
                    <li><a href="https://x.com/xwhatwillhappen?s=21"><img src="{% static 'images/icons8-x.svg' %}" alt="X-Icon"></a></li>
                    <li><a href="https://discord.gg/VHtDWDvy"><img src="{% static 'images/icons8-discord-50.svg' %}" alt="X-Icon"></a></li>
                    <li><a class="nft-launch" href="#"><img  src="{% static 'images/lunch-my-nft-icon.svg' %}" alt="X-Icon"></a></li>
                </ul>
            </section>
        </section>
        <!-- Main Footer Section -->
        <footer>
            <hr>
            <span>Designed by ALISH. </span>
            <p><span>&copy;</span>2025. All rights reserved. </p>
        </footer>
    </main>
    <!-- Auto banner play function  -->
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const video = document.getElementById('myVideo');
            video.play();
        });
    </script>
    <script src="{% static 'js/parent.js' %}"></script>
</body>
</html>

templates/prediction_detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- ========== Meta Data ========== -->
    <meta charset="UTF-8">
    <!-- ========== Page Title ========== -->
    <title>{{ prediction.title }}</title>
    <!-- ========== Style & Fav Icon Links ========== -->
    <link rel="stylesheet" href="{% static 'css/prediction_detail.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/photo_2025-01-30_19-24-58.jpg' %}">
</head>
<body>
    <!-- ========== Loading Page ========== -->
    <div id="loading">
        <div class="loader-content">
            <div class="loader-spinner"></div>
            <p class="loading-text">LOADING ...</p>
        </div>
    </div>
    <!-- ========== Main Section ========== -->
    <div class="container">
        <h1 class="blog-title">{{ prediction.title }}</h1>
        <section class="main-content">
            <p class="content">{{ prediction.content }}</p>
        </section>
        <a href="{% url 'core:Home' %}">Go back to Home</a>
    </div>
    <!-- ========== Loading Function ========== -->
    <script>
        window.addEventListener('load', function () {
        const loader = document.getElementById('loading');
        loader.style.opacity = '0';
        loader.style.transition = 'opacity 0.5s ease';
        setTimeout(() => {
            loader.style.display = 'none';
        }, 500);
        });
    </script>
</body>
</html>